.include "m328PBdef.inc"

.def A=r16
.def B=r17
.def C=r18
.def D=r19
.def TEMP=r20
.def ANOT=r21
.def BNOT=r22
.def CNOT=r23
.def BACKUP_A=r24
.def BACKUP_B=r25
.def BACKUP_C=r26
.def BACKUP_D=r27
.def F0=r28
.def F1=r29

;F0 = (A ? B' + B ? D) || F1= (A?+C?) ? (B?+D)
    
START: clr TEMP
OUT DDRB,TEMP
SER TEMP
OUT PORTB,TEMP
OUT DDRC,TEMP

IN TEMP,PINB ;read PINS FROM PORT B 
MOV A,TEMP ;A IN A'S LSB
ANDI A,1
LSR TEMP
MOV B,TEMP ;B IN B'S LSB
ANDI B,1
LSR TEMP
MOV C,TEMP ;C IN C'S LSB
ANDI C,1
LSR TEMP
MOV D,TEMP ;D IN C'S LSB
ANDI D,1
    
NOP
    
MOV ANOT,A ;AN=A
COM ANOT ;A=A;
ANDI ANOT,1
MOV BNOT,B ;BN = B
COM BNOT ;BN=B'
ANDI BNOT,1
MOV CNOT,C ; CN=C
COM CNOT ; CN=C'
ANDI CNOT,1
    
MOV BACKUP_A,A
MOV BACKUP_B,B
MOV BACKUP_C,C
MOV BACKUP_D,d
  
    
AND A,BNOT ; A = (A*B')
AND B,D ; B = (B*D)
OR A,B ; A = (A ? B' + B ? D)

MOV F0,A ; SET F0 , F0F28

; TIME TO CALCULATE F1

OR ANOT,CNOT ;ANOT = (A'+C')
OR BNOT,D ;BNOT = (B'+D)
AND ANOT,BNOT ;(A'+C')*(B'+D)

ANDI ANOT,1 ;ISOLATE LSB

MOV F1,ANOT ; SET F1 , F1=R29
    
;OUTPUT : F0 2ND LSB, F1 LSB
MOV A,F0 
ANDI A,1 
LSL A
or A,F1
    
OUT PORTC,A    
